 name: 'Automatic build'
 on:
   push:
     branches:
       - main
     paths-ignore:
       - .gitignore
       - README.md
       - LICENSE

 jobs:
   continuous-delivery:

     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           fetch-depth: 0  # for posts's lastmod
           submodules: recursive
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: 3.1
           bundler-cache: true
       - run: bundle install
       - name: Deploy
         run: bash tools/deploy.sh
